spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kasperin_prod
    username: kasperin_prod_user
    password: kasperin
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false